[features]
seeds = false
skip-lint = false
[programs.localnet]
counter_program = "GzkzL8NswLoDM56qpdVp4tsk8rJhXG9aQrhBcTDhLUjt"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "/home/ming070492/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
